### ISSUE TITLE
项目不错: 有几个建议

### ISSUE THREAD

**Issue by hhstore** [xieyezi/flutter-getx-template#5]
- 这个模板目录结构还可以. 
- 不过不确定你有没有看过官方的 [get_cli](https://github.com/jonataslaw/get_cli) 生成的模板目录. 
- 
    - get_cli 除了可以初始化目录, 还可以命令行添加 page/view/controller. 
    - 我看你基于一个 js 的工具, 做脚手架. 
- 我早先也尝试自己定义一个目录, 不过试用官方的`get_cli`生成的目录. 还是决定用官方的目录了. 

## get_cli 支持的指令: 

- 我不确定你有使用过这些指令麽. 
- 这些指令已经足够好用. 我是建议你可以把这个 repo 里, 新增的特性, 提交给官方的脚手架. 

```yml

  get-create-project:
    cmds:
      - get create project:my_app

  # 初始化 app 目录:
  get-init:
    cmds:
      - get init
      - task: mkdir
        vars: {FOLDER: "lib/app/data/locales"}

  # 代码格式化:
  get-sort:
    cmds:
      - get sort

  get-gen-locales:
    desc: "generate multi language(i18n)"
    cmds:
      - get generate locales assets/locales on data/locales

  get-add-page:
    cmds:
      - get create page:$PAGE_NAME # set from .env(check .env.local)

  get-add-sub-page:
    cmds:
      - get create page:$PAGE_NAME on $PAGE_PATH

  get-add-controller:
    cmds:
      - get create controller:$VIEW_NAME on $VIEW_PATH

  get-add-view-only:
    cmds:
      - get create view:$VIEW_NAME on $VIEW_PATH

  get-add-view:
    cmds:
      - task: get-add-view-only
      - task: get-add-controller

  get-provider:
    cmds:
      - get create provider:$PROVIDER_NAME on data

  get-gen-model:
    cmds:
      #- get generate model with assets/models/wallet_address_asset_entity.json --skipProvider
      - get generate model with $MODEL_JSON_FILE_PATH --skipProvider

```

## 几个优化点: 

- 多语言: 官方的 get_cli 支持生成: 不需要手动管理

```
get generate locales assets/locales on data/locales

```

- 基于官方脚手架添加页面, 会自动更新 router. 
- main 文件: Global.init().then() 是个好写法. 不过. 其实 Global 不需要这样定义. 
    - Get.put(), Get.lazyPut() 可以 put 任何东西, 包括全局变量集. 
    - 你可以后续使用 Get.find<xxx>() 方式, 在项目任意位置访问到. 其实间接实现全局变量的效果. 
    - 这样会更方便. 

```
Get.lazyPut<HomeController>(() => HomeController());
```

## anyway: 

- 不是来吵架的哈. 我是看到有同样喜欢 GetX 的开发者. 过来看一下. 😄
- 另外, 我创建了一个技术讨论组 `gossipcoder`. 欢迎加入一起来讨论技术, flutter 或者其他. 
- https://github.com/hhstore/blog/issues/309

### discord 讨论组: 

- https://discord.gg/MnDA9pfWAW
- 删掉了 keybase 的讨论组, 迁移到 discord. 
- 之前选择 keybase, 是觉得没被墙. 还是不够稳定
